title: "MY-TITLE"
date: 2018-10-24

title: 385 MinorAssignment 3
author: SharynBrans
email: sharyn.brand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage for the Minor 3 JSON file assignment.
  Testing how to host on github pages

# social links
twitter_username: sharynbrand
github_username:  tobeheard

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
